### ISSUE TITLE
The training process is unstable.

### ISSUE THREAD

**Issue by johnlanbor** [sfzhang15/ATSS#12]
When I train dcnX101 or X101. The training process is breaking , while report no bugs, and the memory is still occupied, which cause the X101 model is 0.4 lower than you paper mentioned.

and mackrcnn benchmark seems have this issue too.
so, how do you fix that problem?

**Comment by sfzhang15** [comment]
@johnlanbor 
Sorry, we do not seem to have encountered this problem.

**Comment by johnlanbor** [comment]
Thanks, the Dcn X101 has same performance as paper mentioned. but X 101 is 0.4 lower.
That may because the training process is broken by unKnown reason.
I think I can close this issue!
Thanks
