### ISSUE TITLE
RPN-only models don't have roi_heads

### ISSUE THREAD

**Issue by kaikaizhu** [sfzhang15/ATSS#13]
Why RPN-only models don't have roi_heads in class GeneralizedRCNN(nn.Module)？

**Comment by sfzhang15** [comment]
@kaikaizhu 
RPN-only=True means it is one-stage methods, which do not have roi_heads.

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.
