### ISSUE TITLE
RuntimeError: cuda runtime error (98) : invalid device function at atss_core/csrc/cuda/SigmoidFocalLoss_cuda.cu:139

### ISSUE THREAD

**Issue by hust-kevin** [sfzhang15/ATSS#14]
when I train the model, I meet this error.

PS:
`pytorch 1.3, torchvision 0.4 cuda 10.0`

**Comment by sfzhang15** [comment]
@hust-kevin 
You can try to remove the _build_ folder and then build the code again.

**Comment by hust-kevin** [comment]
thanks, I solve this issue by re-build
another question, in your paper said that retinanet ap is 36.3, however in paper and detectron, the ap of retinanet is 35.7

**Comment by sfzhang15** [comment]
@hust-kevin 
Please refer to [this](https://github.com/facebookresearch/maskrcnn-benchmark/pull/102).

**Comment by hust-kevin** [comment]
thanks  for reply
in table 7.  the ap 39.3 actually is come from retinanet + imprs + atss.
did you do experiment about only apply atss on retinanet ? what's the ap of retinanet + atss

**Comment by sfzhang15** [comment]
@hust-kevin 
Sorry about that. We do not do experiment about only applying atss on retinanet. You can try to do this experiment, we believe it will bring some improvement.

**Comment by laisimiao** [comment]
@hust-kevin I also have this issue, but can't be solved by re-build?
