### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 1581: invalid start byte

### ISSUE THREAD

**Issue by pipi2020** [sfzhang15/ATSS#15]
i am so sorry to tell you about this .
when i train my own database ,the error is being
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 1581: invalid start byte
could you tell me how to solve it .Thank U

**Comment by pipi2020** [comment]
@sfzhang15

**Comment by sfzhang15** [comment]
@pipi2020 
In which file did the error occur?

**Comment by sfzhang15** [comment]
I close this issue because there was no response for a long time, please reopen it if there are still problems.
