### ISSUE TITLE
I want use custom dataset

### ISSUE THREAD

**Issue by HansolEom** [sfzhang15/ATSS#19]
How can I learn from my dataset?

**Comment by sfzhang15** [comment]
@HansolEom 
You can refer to [this](https://github.com/tianzhi0549/FCOS/issues/54). If you have any questions, please feel free to contact us.

**Comment by HansolEom** [comment]
Thank you for your reply.
I wonder one more thing.
I want to see a bounding box drawn in my image. Can we do it?
Do I have to make annotations like coco_test_set?

**Comment by HansolEom** [comment]
> @HansolEom
> You can refer to [this](https://github.com/tianzhi0549/FCOS/issues/54). If you have any questions, please feel free to contact us.

Thank you for your reply.

**Comment by HansolEom** [comment]
> > @HansolEom
> > You can refer to [this](https://github.com/tianzhi0549/FCOS/issues/54). If you have any questions, please feel free to contact us.
> 
> Thank you for your reply.


I haven't solved this problem.
I want to learn about 23 classes. But I think I got an error loading 80 models already learned. I want to use pretraine resnet. Is there a way?

Traceback (most recent call last):
  File "tools/train_net.py", line 183, in <module>
    main()
  File "tools/train_net.py", line 179, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 59, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/workspace/ATSS/atss_core/utils/checkpoint.py", line 63, in load
    self._load_model(checkpoint)
  File "/workspace/ATSS/atss_core/utils/checkpoint.py", line 99, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"))
  File "/workspace/ATSS/atss_core/utils/model_serialization.py", line 82, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/opt/conda/envs/ATSS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
	size mismatch for module.rpn.head.cls_logits.weight: copying a param with shape torch.Size([80, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([23, 256, 3, 3]).
	size mismatch for module.rpn.head.cls_logits.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([23]).

**Comment by sfzhang15** [comment]
@HansolEom 
If your 23 classes is the subset of COCO 80 classes, you can chose the 23 channels from the 80 channels of the classification prediction layer and save this model to use. If not, you can drop the weights of the classification prediction layer and save it to use as pretrain.
