### ISSUE TITLE
where should i use TEST.BBOX_AUG.ENABLED=True to realize multi-scale testing

### ISSUE THREAD

**Issue by daiwc** [sfzhang15/ATSS#21]
I use the atss_demo.py to test image ,and set the TEST.BBOX_AUG.ENABLED=True in atss_core/config/defaults.py , but it didn’t work.

**Comment by sfzhang15** [comment]
@daiwc 
If you want to test your model with multi-scale testing on one dataset, you should use [test_net.py](https://github.com/sfzhang15/ATSS/blob/master/tools/test_net.py) and atss_demo.py maybe not support multi-scale.

**Comment by daiwc** [comment]
can i use&nbsp;&nbsp;test_net.py&nbsp;to test my own dataset?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shifeng Zhang"<notifications@github.com&gt;; 
发送时间: 2020年3月1日(星期天) 下午2:17
收件人: "sfzhang15/ATSS"<ATSS@noreply.github.com&gt;; 
抄送: "戴伟聪"<493980892@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [sfzhang15/ATSS] where should i use TEST.BBOX_AUG.ENABLED=True to realize multi-scale testing (#21)




@daiwc
 If you want to test your model with multi-scale testing on one dataset, you should use test_net.py and atss_demo.py maybe not support multi-scale.

**Comment by daiwc** [comment]
> @daiwc
> If you want to test your model with multi-scale testing on one dataset, you should use [test_net.py](https://github.com/sfzhang15/ATSS/blob/master/tools/test_net.py) and atss_demo.py maybe not support multi-scale.

**Comment by daiwc** [comment]
@sfzhang15 should i use test_net.py to test my own dataset?

**Comment by sfzhang15** [comment]
@daiwc 
If you want to display detection results for an image, you should use atss_demo.py that only supports single-scale. If you want to evaluate on your own dataset, you should use test_net.py that supports single-scale and multi-scale.

**Comment by daiwc** [comment]
@sfzhang15  I have realized use multi-scale to test image, but i found that when the density of target become higher, the precision will become lower. some times recognize the head of person or the arm of person as person ,even though the person have already found!

**Comment by daiwc** [comment]
@sfzhang15 Is this phenomenon normally?
