### ISSUE TITLE
How many epochs did you run?

### ISSUE THREAD

**Issue by HansolEom** [sfzhang15/ATSS#23]
max_iter = 180k
coco_trainval = 35k
I think it's about 5 epochs if you calculate it with epoch.
If my dataset is 60k, is it right to run 300k?

**Comment by sfzhang15** [comment]
@HansolEom 
For the 2x lr schedule, the total iteration is 180k with batch size 16, and coco_train2017 has 118287 images, thus the corresponding epoch is 180K*16/118287.
