### ISSUE TITLE
Will there be a Detectron2 implementation?

### ISSUE THREAD

**Issue by SkeletonOne** [sfzhang15/ATSS#27]
Thx for your great work. Btw, will there be a detectron2 implementation? If so, when will it release?

**Comment by sfzhang15** [comment]
@SkeletonOne 
We have reimplemented FCOS and ATSS on Detectron2. Based on them, we have done a new work.
All the codes will be organized and then released later.

**Comment by SkeletonOne** [comment]
@sfzhang15 Great! Looking forward to your new work.
