### ISSUE TITLE
Is ATSS suitable for detecting large aspect ratio objects?

### ISSUE THREAD

**Issue by feiyuhuahuo** [sfzhang15/ATSS#28]
According to the paper, ATSS is insensitive to aspect ratios and scales. Only one anchor per location can get a good result. But this situation is for COCO dataset. Most objects in COCO do not have a large aspect ratio. For industrial inspections, some defects may have really large aspect ratios (e.g. 1: 10). So is ATSS suitable for this situation? Anyway, the similar the anchor and the gt_box are, the easier it is for the network to learn.

**Comment by sfzhang15** [comment]
@feiyuhuahuo 
Since I have been busy with PhD graduation related matters recently, I have not had time to try ATSS on other datasets, so I can not give you a clear answer. You can run some experiments on your own dataset. If you have any questions, please feel free to communicate.
