### ISSUE TITLE
hello,can this code run on windows?

### ISSUE THREAD

**Issue by DTW1004** [sfzhang15/ATSS#29]
I am work on windows,when run your code, see your install list ,it needs to install gcc? but windows can't, and when install other modules, there are lots of problems...  so how to run it on windows?

**Comment by sfzhang15** [comment]
@DTW1004 
I recommend you to run this code under linux, because I have no experiences about running code in windows and might not be able to solve your problems. Besides, if you can run the specific version of PyTorch on windows, I think this code also can be run on windows.

**Comment by pmj828** [comment]
if I have not GPU in linux, is it can run??

**Comment by sfzhang15** [comment]
@pmj828 
During inference, [ml_nms](https://github.com/sfzhang15/ATSS/blob/master/atss_core/csrc/ml_nms.h) is used, which does not support CPU. You can try to use [nms](https://github.com/sfzhang15/ATSS/blob/master/atss_core/csrc/nms.h).
