### ISSUE TITLE
RetinaNet : Anchor box offsets and GIoU loss

### ISSUE THREAD

**Issue by ajoseph12** [sfzhang15/ATSS#30]
Hey Shifeng Zhang,
Thank you for the extremely interesting analysis you and the co-authors put forth in the paper. I, however, have a question concerning the implementation of FCOS modules within RetinaNet, the GIoU loss module to be more precise. 
As you must be aware, the smooth_l1 loss calculated during RetinaNet training is on anchor box offsets, i.e tx, ty, tw and th and not bounding box offsets x1, y1, x2 and y2. To this end, my questions are as follows :
- While training RetinaNet with GIoU loss did you skip the bounding transformation (x1, y1, x2, y2 to tx, ty, tw, th) and compute the GIoU loss on the bounding box values (ground-truth and prediction) rather than the offsets? Or was the training effectuated using a different methodology?
- While incorporating the GIoU loss, did you modify the network architecture (Eg: applying an exp() transform on regression outputs) in any way to accommodate for this change?
Thank you for your response :)

**Comment by sfzhang15** [comment]
@ajoseph12 
[Here](https://github.com/sfzhang15/ATSS/blob/master/atss_core/modeling/rpn/atss/loss.py#L36-L77) is the code of GIoU loss.
1. The GIoU loss must be computed on the bounding box values (ground-truth and prediction) not the offsets. As codes show, the offsets first need to decode to bboxes and then are used for the GIoU loss. Besides, for the SmoothL1 loss, we have tried different regression targer including (x1, y1, x2, y2), (x1, y1, w, h) and (tx, ty, tw, th) on RetinaNet, their performances are similar.
2. No. We just decode the offsets to bboxes and then compute the GIoU loss on predicted bboxes and gt bboxes.

**Comment by ajoseph12** [comment]
Thank you for your response :)
