### ISSUE TITLE
 the P and N

### ISSUE THREAD

**Issue by henbucuoshanghai** [sfzhang15/ATSS#32]
I dnt ubderstand.  the P and N is total the same as the  original anchors of all levels????
the number is the same as the  original???

**Comment by sfzhang15** [comment]
@henbucuoshanghai 
I don't quite understand your problem, please describe it in detail, or use Chinese.

**Comment by henbucuoshanghai** [comment]
。。

**Comment by henbucuoshanghai** [comment]
P和N总量和           原始所有leves的anchor是一样的？
anchors是一样的 和当初？

**Comment by sfzhang15** [comment]
先选出候选正样本，然后在选出最终的正样本，P是最终的正样本，剩下的都是N
