### ISSUE TITLE
Have you tried ATSS on the original RetinaNet?

### ISSUE THREAD

**Issue by feiyuhuahuo** [sfzhang15/ATSS#33]
I noticed that all your experiments follow this order: original detector --> Imprs --> ATSS. Have you tried this order: original detector --> ATSS ? I just want to know which trick in Imprs is unnecessary due to the existence of ATSS. Because from my opinion, ATSS helps to balance the numbers of the matched anchors for each gt box and improved the match quality. So maybe one or more tricks in Imprs is useless or have less effect, e.g. In GT Box ? Because they are doing the same things. Any insights?

**Comment by sfzhang15** [comment]
@feiyuhuahuo 
ATSS is not limited to but compatible with these imprs.
Limiting  positives in GT box is to use centerness.
