### ISSUE TITLE
class num

### ISSUE THREAD

**Issue by JUNXYU** [sfzhang15/ATSS#34]
在ATSSHead中，num_classes = cfg.MODEL.ATSS_NUM_CLASSES - 1,这个是不是意味着你只计算了前景类别的得分?而且focal loss计算class loss，哪里似乎也没有考虑到背景，会不会存在问题？

**Comment by sfzhang15** [comment]
@JUNXYU 
softmax做多分类需要单独考虑背景这一类，而focal loss默认采用的是sigmoid来做多分类，不需要单独考虑背景这一类，正常情况下检测是不需要输出背景这一类的预测结果。如果真要计算sigmoid多分类的背景类别的输出，按照我理解应该是(1-c1)*...*(1-cn)。

**Comment by JUNXYU** [comment]
谢谢解答这个问题，在阅读代码的时没有意识到这点的差异， 现在理解了。
