### ISSUE TITLE
What is the difference between 'In GT Box' and 'Spatial constraint'

### ISSUE THREAD

**Issue by leeesangwon** [sfzhang15/ATSS#37]
Thank you for sharing your great works!

I'm wondering what is the difference between the `In GT Box` on the Table 1 and the `Spatial constraint` on the Figure 1.
When I first read your paper, I understood that the `In GT Box` and `Spatial constraint` is the same based on the description below.
> limiting positive samples in the ground-truth box [56]

However, on the table 2, you compared the score of the `Intersection over Union` and `Spatial and Scale Constraint` in spite of the score of the `IoU` includes the improvement from the `In GT Box`.

It makes me confusing whether `In GT Box` and `Spatial Constraint` are different operation.

Thank you in advances for your help!

**Comment by sfzhang15** [comment]
@leeesangwon 
`Spatial Constraint` can ensure `In GT Box`, while `IoU` can not, i.e., IoU may select some positive anchors whose center are on the outside of GT box, thus we limit positives in GT box.

**Comment by leeesangwon** [comment]
1. Then what I understood are:
    - Both `RetinaNet + imprs. (Intersection over Union)` and `FCOS (Spatial and Scale Constraint)` in table 2 have the spatial constraint.
    - The 0.8 performance gap comes from whether using all candidate boxes on the corresponding pyramid level or selecting boxes using the IoU threshold.

    Did I understand correctly?

2. If I did, I have one more question.  

    As you commented, the IoU threshold can not ensure the matched anchor box is in the GT box.  
    However, I think it can if the IoU threshold is large enough.  
    For example, RetinaNet uses 0.5 as the threshold and it seems sufficient condition. (Please refer to my low-quality figure below)
    ![image](https://user-images.githubusercontent.com/19677551/80501872-ebb25500-89aa-11ea-948f-de7de8d9b5fa.png)

    But you could improve performance after limiting positives in the GT box.
    Please let me know where is the points I missed!

Thank you!

**Comment by sfzhang15** [comment]
@leeesangwon 
1. As for RetinaNet + imprs. (Intersection over Union) and FCOS (Spatial and Scale Constraint) in table 2, their final positive samples are limited in GT box. But the spatial constraint is a step for FCOS to select candicate positives. The 0.8 performance gap comes from how to select final positives from those anchors in GT box across all pyramid levels.
2. If [allow_low_quality_matches=False](https://github.com/sfzhang15/ATSS/blob/master/atss_core/modeling/matcher.py#L78), you are right, but allow_low_quality_matches=True.

**Comment by leeesangwon** [comment]
Now everything becomes crystal clear!
Thanks again your super fast reply!! 🚀
