### ISSUE TITLE
Is there an unfair comparsion?

### ISSUE THREAD

**Issue by huizhang0110** [sfzhang15/ATSS#38]
I noticed datasets config difference between ATSS and FCOS.
For ATSS,
![image](https://user-images.githubusercontent.com/32508847/80804209-0bce5800-8be7-11ea-8463-bbc5957008db.png)
For FCOS,
![image](https://user-images.githubusercontent.com/32508847/80804233-1b4da100-8be7-11ea-9992-fe21800976c1.png)

**Comment by sfzhang15** [comment]
@huizhang0110 
coco_2017_train=coco_2014_train+coco_2014_valminusminval
coco_2017_val=coco_2014_minval

**Comment by huizhang0110** [comment]
Thanks for your reply, but I think there are some differences.
![image](https://user-images.githubusercontent.com/32508847/80818540-f3ba0100-8c05-11ea-8fa6-821e0eefe223.png)
```
        "coco_2017_train": {
            "img_dir": "coco/train2017",
            "ann_file": "coco/annotations/instances_train2017.json"
        },
        "coco_2017_val": {
            "img_dir": "coco/val2017",
            "ann_file": "coco/annotations/instances_val2017.json"
        },
```
```
        "coco_2014_train": {
            "img_dir": "coco/train2014",
            "ann_file": "coco/annotations/instances_train2014.json"
        },
        "coco_2014_minival": {
            "img_dir": "coco/val2014",
            "ann_file": "coco/annotations/instances_minival2014.json"
        },
        "coco_2014_valminusminival": {
            "img_dir": "coco/val2014",
            "ann_file": "coco/annotations/instances_valminusminival2014.json"
        },
```

**Comment by huizhang0110** [comment]
sorry, you are right!
 size(minival2014) = 5G

**Comment by huizhang0110** [comment]
Sorry, you are right. Thanks for  your reply.
