### ISSUE TITLE
I encouter an error when runing demo

### ISSUE THREAD

**Issue by ZexinYan** [sfzhang15/ATSS#4]
I have encounter an error when running demo. 
`  File "/git/ATSS/atss_core/modeling/rpn/atss/inference.py", line 93, in forward
    boxlists = self.select_over_all_levels(boxlists)
  File "/git/ATSS/atss_core/modeling/rpn/atss/inference.py", line 106, in select_over_all_levels
    result = boxlist_ml_nms(boxlists[i], self.nms_thresh)
  File "/git/ATSS/atss_core/structures/boxlist_ops.py", line 55, in boxlist_ml_nms
    keep = _box_ml_nms(boxes, scores, labels.float(), nms_thresh)
RuntimeError: Not compiled with GPU support (ml_nms at atss_core/csrc/ml_nms.h:23)
`

Cound you help me fix this error?

**Comment by yqyao** [comment]
Do you run the ''python setup.py build develop --no-deps'' ? @ @ZexinYan

**Comment by ZexinYan** [comment]
> Do you run the ''python setup.py build develop --no-deps'' ? @ @ZexinYan

Yes, I have run it.

**Comment by sfzhang15** [comment]
@ZexinYan 
This looks like a problem with cuda, you can refer to [this issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/230).

**Comment by ZexinYan** [comment]
> @ZexinYan
> This looks like a problem with cuda, you can refer to [this issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/230).

Thanks for your help, it really works.
