### ISSUE TITLE
when use 3 anchors per pixel， ATSS performance become lower。

### ISSUE THREAD

**Issue by lji72** [sfzhang15/ATSS#41]

**Comment by lji72** [comment]
When I use FCOS +ATSS model from mmdetection framework to try 3 anchors per pixel , ACC become 37.6% from 39.2%, which is quite strange. Can you give me some suggestions to make it work.

**Comment by lji72** [comment]
when I use 3 anchor per pixel, need top_k  be triple?

**Comment by sfzhang15** [comment]
@lji72 
1. How are the 3 anchors set?
2. If you use the newest codes, it will automatically change the topk as the anchor number per location changes at this [line](https://github.com/sfzhang15/ATSS/blob/master/atss_core/modeling/rpn/atss/loss.py#L153).

**Comment by lji72** [comment]
@sfzhang15 many thanks!

**Comment by wanghao14** [comment]
@lji72 Hi, as far as I am understand, if you put more anchors in each location, the location which is closer to the groundtruth will provide more anchors when computing the l2 distance. So the anchors you pick will mostly from the same location if you don't change the topk.
So have you changed the topk and what is your performance?
