### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by hzh8311** [sfzhang15/ATSS#43]
hi, I have run the `ATSS_dcnv2_R_50_FPN_1x` model with atss_demo.py and `min-image-size=1080/800` settings, average inference time is 400/360ms for 100 images.  I used M40 gpu and without saving result images.

it is far away with your inference time 54ms, what is your test settings?

**Comment by sfzhang15** [comment]
Please refer to [this issue](https://github.com/tianzhi0549/FCOS/issues/108).
