### ISSUE TITLE
Add ATSS to RPN

### ISSUE THREAD

**Issue by thisisi3** [sfzhang15/ATSS#48]
Hi,
Really good work!
It seems RPN here also supports ATSS sampler, I am wondering if you've tested it in any model (e.g. FasterRCNN) on any dataset? If so do you mind sharing the configuration and the benchmark, thanks.

**Comment by thisisi3** [comment]
In other words, have you tested ATSS on two stage detectors' RPN and how well does it work?

**Comment by sfzhang15** [comment]
@thisisi3 
Sorry about that. We have not tested ATSS on two stage detectors, you can try it.
