### ISSUE TITLE
about ab and af inconsistency

### ISSUE THREAD

**Issue by zhenghao977** [sfzhang15/ATSS#51]
hi, I have a question. How to improve RetinaNet by using the (In GT Box, Centerness and Scalar).
Just use the FCOS code and put every pixel an anchor and use anchor-base IoU to define the pos-neg sample and predict the offset from the anchor? thank you very much!

**Comment by sfzhang15** [comment]
@ChingHo97 
If you want to improve RetinaNet, you can use the codes of RetinaNet and add those improvements (In GT Box, Centerness and Scalar) to it.
