### ISSUE TITLE
About FCOS+ATSS in Table 3

### ISSUE THREAD

**Issue by youngwanLEE** [sfzhang15/ATSS#52]
Hi,

Can I train FCOS+ATSS model in Table 3 on your repo?

thanks

**Comment by sfzhang15** [comment]
@youngwanLEE 
Yes, you can set [REGRESSION_TYPE](https://github.com/sfzhang15/ATSS/blob/master/atss_core/config/defaults.py#L320) from BOX to POINT to train FCOS + ATSS.

**Comment by youngwanLEE** [comment]
@sfzhang15 

Thanks !!
