### ISSUE TITLE
where is the code of ATSS specifically?

### ISSUE THREAD

**Issue by liushuai839** [sfzhang15/ATSS#54]
hi,guys,thanks for your paper and code.
but  I really want to know that where is  code of ATSS specifically?  In which py  file...   
Is it  in ATSS-master/atss_core/modeling/rpn/atss/atss.py ???

**Comment by sfzhang15** [comment]
@liushuai839 
The implementaion of ATSS is [here](https://github.com/sfzhang15/ATSS/blob/master/atss_core/modeling/rpn/atss/loss.py#L131-L189).
