### ISSUE TITLE
question about table2

### ISSUE THREAD

**Issue by xulingzhi951118** [sfzhang15/ATSS#56]
![image](https://user-images.githubusercontent.com/29685301/88475500-ff963480-cf62-11ea-802b-fa0350082603.png)
请问在table2的实验中，FCOS具体是如何使用IOU的策略来选择正负样本的呢？

**Comment by sfzhang15** [comment]
@xulingzhi951118 
先把FCOS的anchor point变成retinanet的anchor box（其中anchor box的中心点就是anchor point），然后利用IoU划分正负样本，再把正样本的anchor box返回成anchor point，按照FCOS的方式来回归。

**Comment by xulingzhi951118** [comment]
好的，谢谢您的回答 @sfzhang15
