### ISSUE TITLE
How do I learn multiple anchors?

### ISSUE THREAD

**Issue by HansolHyewon** [sfzhang15/ATSS#58]
I would like to test anchors of various sizes.
As far as I understand, if ㅑ change aspect_rtios to [1.0, 0.5, 1.5] or [(1,1), (2,1),(1,2)], do you think there are 3 anchors? 
I want to adjust. If so, can I adjust scales_per_octave = 3?

**Comment by sfzhang15** [comment]
@HansolEom 
1. You can change [ASPECT_RATIOS](https://github.com/sfzhang15/ATSS/blob/master/configs/atss/atss_R_50_FPN_1x.yaml#L14) to [1.0, 0.5, 1.5] or [(1,1), (2,1),(1,2)] to learn anchors with three differents aspect ratios per location.
2. You can change [SCALES_PER_OCTAVE](https://github.com/sfzhang15/ATSS/blob/master/configs/atss/atss_R_50_FPN_1x.yaml#L15) to 3 and [ANCHOR_SIZES](https://github.com/sfzhang15/ATSS/blob/master/configs/atss/atss_R_50_FPN_1x.yaml#L13) to (32, 64, 128, 256, 512) to learn anchors with three differents scales per location.
