### ISSUE TITLE
How to clarify it is a better target assigner rather than a noise added in the label????

### ISSUE THREAD

**Issue by AlexWang1900** [sfzhang15/ATSS#59]
I used similar method , th = ious.mean()- ious.std(), where ious = [max iou for each target box  for all anchor pair].
it seems to me the th variation alone can boost the MAP.

**Comment by sfzhang15** [comment]
@AlexWang1900 
1. ious = [max iou for each target box for all anchor pair] means that if there is only one gt in an image, ious only has one value?
2. Your method can boost the AP, how many points can it improve?

**Comment by AlexWang1900** [comment]
1）It can be max like 5 layers * A anchors have target assigned in that case.&nbsp; even only one anchor got assigned,it doesn't matter because loss is calculated per batch.&nbsp;
but in that case your method may assigned 9 anchors without IOU per layer. it makes too much noise.&nbsp;
2)It can boost 1% -2%&nbsp;


HOW do you clarify your method a assignment better than random choice in which it brings a small noise to overfit the test set??? especially you made an assumption there is a normal distribution for anchors "suit points" to labels.&nbsp; in that case there must exist a random choice which can achieve your method's boost.&nbsp;



---Original---

**Comment by sfzhang15** [comment]
@AlexWang1900 
1. I do not understand your method. You can describle your method and question in Chinese for better comunication.
2. It boost ATSS from 40.3% to ~42% on MS COCO?
