### ISSUE TITLE
Why don't you need to set the ignore area

### ISSUE THREAD

**Issue by hhaAndroid** [sfzhang15/ATSS#6]
Most paper label designs use ignore areas because it is difficult for hard samples，ATSS does not need to be set, I am confused

**Comment by sfzhang15** [comment]
@hhaAndroid 
RetinaNet ignores these anchors whose IoU is between 0.4~0.5, FCOS does not ignore samples.  ATSS does not ignore samples, because ignoring samples will introduce a hyperparameter.

**Comment by hhaAndroid** [comment]
thank you
