### ISSUE TITLE
what is your final model used by ATSS in table 8?

### ISSUE THREAD

**Issue by HyogiJeon** [sfzhang15/ATSS#60]
Hello.

I saw your paper and I have 1 question.
What is your final model used by ATSS in table 8?

And I also saw the README.
You posted (i.e., consistent with models in FCOS and maskrcnn_benchmark).
Which model do you used for ATSS?
FCOS? or maskrcnn?

Thank you in advances for your help!

**Comment by sfzhang15** [comment]
@HyogiJeon 
1. Our final models in Table 8 are the improved RetinaNet (#A=1) with ATSS.
2. ATSS uses the codes of FCOS to implement, and FCOS uses the codes of maskrcnn to implement.

**Comment by HyogiJeon** [comment]
Thank you for your answer.
And I have some additional question.

1. You said that the final model is the improved RetinaNet (#A=1) with ATSS.
Then, is it right the same model in Table 3 and in Table 8?
But, they have difference MAP.(39.3 in Table 3, 43.6 in Table 8)

2. Is it right the model posted in a paper and the model in your code are difference?

Thank you.

**Comment by sfzhang15** [comment]
@HyogiJeon 
1. Yes. Please see the first paragraph in Sec 4.4 for their training differences.
2. No, it is the same.
