### ISSUE TITLE
centerness branch shares convs with cls or reg?

### ISSUE THREAD

**Issue by huanyuxinchen** [sfzhang15/ATSS#61]
Hello,
    Thanks for your great work. I found a problem: in the FCOS paper, centerness branch shares convs with cls branch, but in your code,  centerness branch shares convs with reg branch. Why different?

**Comment by sfzhang15** [comment]
@huanyuxinchen 
We use the improved version of FCOS, which moves the centerness branch from cls to reg because of better performance. Please refer to theTable 3 in the FCOS newest paper.
