### ISSUE TITLE
对于ATSS，是否可以适用于其他keypoint based的网络？

### ISSUE THREAD

**Issue by JoJoliking** [sfzhang15/ATSS#62]
想请问下您，ATSS是否在Keypint Based的网络上进行测试过，或者说是否适用？如：CenterNet，ConterNet等

**Comment by sfzhang15** [comment]
@JoJoliking 
Keypint Based算法的检测流程不大一样，ATSS不能直接应用于它们，但是对每个物体adaptive的选取正负样本的思想可以尝试借鉴一下
