### ISSUE TITLE
网络模型切换

### ISSUE THREAD

**Issue by SnailForce** [sfzhang15/ATSS#64]
您好，有幸听了您在valse上的演讲，在跑代码时遇到几个问题想请教一下。
如何切换fcos和retinanet的网络模型？
configs/atss 默认使用的是retinanet吗？
如果是retinanet的话，跑configs/atss 时会出现的中心度损失意味着什么？

**Comment by sfzhang15** [comment]
@SnailForce 
ATSS里面默认的是改进版的RetinaNet+ATSS，改进版的RetinaNet就是论文里表格1里面显示的，原版的RetinaNet请使用RetinaNet的config文件
改进版的RetinaNet添加了FCOS的中心度分支
