### ISSUE TITLE
topk设置

### ISSUE THREAD

**Issue by zuop-star** [sfzhang15/ATSS#65]
在文章里面，RetinaNet在anchor=9使用的ATSS在实验中topk设置为9吗，效果如何，在这个代码里面好像没有说到论文里在retinanet上的实验

**Comment by sfzhang15** [comment]
@zuop-star 
TOPK是9，不过如[这一行代码所示](https://github.com/sfzhang15/ATSS/blob/master/atss_core/modeling/rpn/atss/loss.py#L153)，会把topk*num_anchor_per_location，所以anchor=9且topk=9时，是每一个层选81个候选正样本
