### ISSUE TITLE
[Question] Is YOLO series applicable? 

### ISSUE THREAD

**Issue by CaptainEven** [sfzhang15/ATSS#67]
As we know, yolo make the grid cell(anchors in the cell) to detect the object which falls into the corresponding grid cell, and ATSS select anchors using L2 distance,  so maybe ATSS is not applicable to YOLOV3/V4?

**Comment by sfzhang15** [comment]
@CaptainEven 
YOLOV3/V4 are based on the anchor, ATSS should be applicable to them.

**Comment by CaptainEven** [comment]
@sfzhang15 Firstly, the anchor is anchor point in FCOS, but anchor box in YOLO, the anchor number is very different(i.e. a fix number of acnhor(i.e.3) per grid cell in YOLO, but much more dense in FCOS and the number of anchor point is varying too), secondly, your ATSS anchor selection is based on L2 distance, but in YOLO, the acnhor bxo attached to each grid cell is naturally the closest anchor for the corresponding grid cell which  GT box falls into, so ATSS will not work and will not have a different selection. So i do not think ATSS will work or be applicable to YOLO.

**Comment by sfzhang15** [comment]
@CaptainEven 
1. Using ATSS needs the anchor box, thus we change the anchor point in FCOS to the anchor box temporarily so as to apply ATSS on FCOS.
2. RetinaNet (#A=9) has 9 anchor boxes per grid cell and it can use ATSS,  thus YOLOv3/v4 with 3 anchor boxes per grid cell can also use ATSS.
3. The adaptiveness of ATSS is to select positive samples according to the characteristics of each GT, this idea can be applied to other detectors.
