### ISSUE TITLE
"WorkerId": an object with that name is already defined

### ISSUE THREAD

**Issue by manhongnie** [sfzhang15/ATSS#69]
terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "WorkerId": an object with that name is already defined
第一次跑下只是在读取图片的时候，报错了，读取第二遍的时候 ，报了这个错误，不知道什么原因

**Comment by manhongnie** [comment]
python3    tools/train_net.py \
    --config-file configs/atss/atss_R_50_FPN_1x.yaml \
    SOLVER.BASE_LR 0.001 \
    SOLVER.IMS_PER_BATCH 4 \
    DATALOADER.NUM_WORKERS 2 \
    OUTPUT_DIR training_dir/atss_R_50_FPN_1x

**Comment by jeff62802217** [comment]
兄弟你这个问题解决了吗，求帮助
