### ISSUE TITLE
Excuse me, I have some problem when train the model, it seems that the _C.cpython file have some problem, and I have compile the setup.py for several times, it still not working, can you do me a favor? Thank you...

### ISSUE THREAD

**Issue by Wastoon** [sfzhang15/ATSS#7]
from atss_core import _C
ImportError: /data/mry/code/ATSS/atss_core/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Comment by sfzhang15** [comment]
@Wastoon 
This seems to be a problem with the CUDA link library. I search some solutions[1](https://devtalk.nvidia.com/default/topic/487773/linking-to-c-object/), [2](https://github.com/voutcn/megahit/issues/35), you can try it.

**Comment by Wastoon** [comment]
@sfzhang15 Thank you so much, I just degrade the CUDA version from 10.1 to 9.0, and it works well now, thanks your project and help...
