### ISSUE TITLE
How about employing the IoU between prediction box and ground truth

### ISSUE THREAD

**Issue by Xudangliatiger** [sfzhang15/ATSS#70]
In original paper and this repo, the IoU is calculated by anchor box and ground truth, which means the sampling results will not change from the begining to the end. How do you think of it?  Have you ever tried replace it with the predicted IoU? I will be appreciate if you could help me about this question.

**Comment by sfzhang15** [comment]
@Xudangliatiger 
If I remember correctly, we should have tried this method. The performance has deteriorated. The possible reason is that a sample will be positive for a while and negative for a while, resulting in unstable training.

**Comment by Xudangliatiger** [comment]
I see. Thanks
