### ISSUE TITLE
About Centerness test

### ISSUE THREAD

**Issue by jianjiandandande** [sfzhang15/ATSS#74]
How do you add Centerness to retinanet.
![image](https://user-images.githubusercontent.com/15951818/95712824-0e55d300-0c98-11eb-9d95-3d0e2be89da2.png)

**Comment by sfzhang15** [comment]
@jianjiandandande 
You can change the anchor box to the anchor point (i.e., the center point of the anchor box), then use the anchor point for the Centerness branch.
