### ISSUE TITLE
so slow

### ISSUE THREAD

**Issue by mytk2012** [sfzhang15/ATSS#76]
Appreciate for your commitment!I have test your code，but fps is so slow，as a one-stage detection，can you explain it?

**Comment by sfzhang15** [comment]
@mytk2012 
Inference time is different according to GPU, pytorch version, CUDA, etc. I quoted the inference time from [FCOS](https://github.com/tianzhi0549/FCOS), more details about the inference time, please refer to [this issue](https://github.com/tianzhi0549/FCOS/issues/108).
