### ISSUE TITLE
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by Alan-D-Chen** [sfzhang15/ATSS#78]
When I run the atss_X_101_32x8d_FPN_2x.yaml , I get this problem  `RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity` , but before "iter: 32240  
" ,that is OK
What should I do?? please~~~

**Comment by sfzhang15** [comment]
@Alan-D-Chen 
Please refer to [this](https://www.cnblogs.com/shenggang/p/12133039.html).
