### ISSUE TITLE
I need some help,please.

### ISSUE THREAD

**Issue by Alan-D-Chen** [sfzhang15/ATSS#80]
hi,Shifeng Zhang,
You did a such great job! But I need some help for you, I find a lot of  yaml files  in  ATSS/config/retinaet? and  ATSS/config/fcos/, and I wanna check them with `python tools/test_net.py  ~~~~~`.where can I find these Corresponding  .pth files.

**Comment by sfzhang15** [comment]
@Alan-D-Chen 
You can find in [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) and [FCOS](https://github.com/tianzhi0549/FCOS).
