### ISSUE TITLE
Who has actually trained this model? The effect of my training model is quite different！

### ISSUE THREAD

**Issue by Alan-D-Chen** [sfzhang15/ATSS#81]
`python -m torch.distributed.launch --nproc_per_node=2 --master_port=$((RANDOM+10000)) tools/train_net.py --config-file configs/atss/atss_R_50_FPN_1x.yaml DATALOADER.NUM_WORKERS 2 OUTPUT_DIR training_dir/atss_R_50_FPN_1x
`
and the result is  
** Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.290
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.435
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.311
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.156
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.322
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.376
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.282
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.479
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.510
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.287
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.561
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.678
**

**Comment by Alan-D-Chen** [comment]
the result from GitHub is 39.3%

**Comment by Alan-D-Chen** [comment]
请问谁那里有完整训练好的模型.pth文件 大约260M
请问谁那里有完整训练好的模型.pth文件 大约260M
▲
Who has a complete training model     PTH file is about 260m,please!!~~

**Comment by Alan-D-Chen** [comment]
PLaese,I need help!

**Comment by sfzhang15** [comment]
The configs are made for 8-GPU training. To train on 1, 2 or 4 GPUs, you should keep the total batch size = 16, which will obtain the same result as 8-GPU. If the total batch size can not be 16, you may need to [change some parameters](https://arxiv.org/abs/1706.02677), but the performance will be different.
