### ISSUE TITLE
SSD centerness

### ISSUE THREAD

**Issue by yyfyan** [sfzhang15/ATSS#9]
In the SSD framework, Can I use centerness? how use the it?

**Comment by sfzhang15** [comment]
@yyfyan 
You can use centerness, but you need to limit all positive samples' center in GT box. Then all other operation is the same as FCOS.

**Comment by yyfyan** [comment]
Thanks.
I add centerness to ssd-like network as like ATSS. During training, I find the centerness loss drop only at early iters,  and the loss keep stable. Have you meet the same problrm?  What's more, I used the normalized anchor([0-1]) instead of [0-height] range to compute centerness targets and GIOU loss.

**Comment by yyfyan** [comment]
@sfzhang15

**Comment by sfzhang15** [comment]
@yyfyan 
Yes, the centerness loss drops only at early iters. You can train ATSS to check the change of the centerness loss.
